DECLARE @CardNo nvarchar(100)
DECLARE TEMP CURSOR FOR SELECT * FROM [DataCenter].[dbo].[CardNo]
OPEN TEMP
FETCH NEXT FROM TEMP INTO @CardNo
WHILE(@@FETCH_STATUS=0)
BEGIN
INSERT INTO [Platform_BT].[dbo].[CardNo]([CardNo]) VALUES(@CardNo)
FETCH NEXT FROM TEMP INTO @CardNo
END
CLOSE TEMP
DEALLOCATE TEMP
GO