
DECLARE @ID int
DECLARE @C6ID nvarchar(100)
DECLARE @GID uniqueidentifier
DECLARE TEMP CURSOR FOR SELECT DeptID, CONVERT(int,UnitID) AS ID FROM C6.dbo.Department WHERE UnitID IS NOT NULL AND UnitID <> '' AND DeptDelFlag = 0
OPEN TEMP
FETCH NEXT FROM TEMP INTO @C6ID, @ID
WHILE(@@FETCH_STATUS=0)
BEGIN
	SELECT @GID = G_ID FROM DataCenter.dbo.Department WHERE ParentId IS NULL AND [Status] = 'N' AND ID = @ID
	UPDATE C6.dbo.Department SET UnitID = @GID WHERE DeptID = @C6ID
	FETCH NEXT FROM TEMP INTO @C6ID, @ID
END
CLOSE TEMP
DEALLOCATE TEMP