
DECLARE @ID int
DECLARE @C6ID nvarchar(100)
DECLARE @GID uniqueidentifier
DECLARE TEMP CURSOR FOR SELECT DeptID, CONVERT(int,BMID) AS ID FROM C6.dbo.Department WHERE BMID IS NOT NULL AND BMID <> '' AND DeptDelFlag = 0
OPEN TEMP
FETCH NEXT FROM TEMP INTO @C6ID, @ID
WHILE(@@FETCH_STATUS=0)
BEGIN
	SELECT @GID = G_ID FROM DataCenter.dbo.Department WHERE ParentId IS NOT NULL AND [Status] = 'N' AND ID = @ID
	UPDATE C6.dbo.Department SET BMID = @GID WHERE DeptID = @C6ID
	FETCH NEXT FROM TEMP INTO @C6ID, @ID
END
CLOSE TEMP
DEALLOCATE TEMP