
DECLARE @Account nvarchar(100)
DECLARE @C6ID nvarchar(100)
DECLARE @GID uniqueidentifier
DECLARE TEMP CURSOR FOR SELECT UserID, LoginCode AS ID FROM C6.dbo.Users WHERE SysFlag = 0
OPEN TEMP
FETCH NEXT FROM TEMP INTO @C6ID, @Account
WHILE(@@FETCH_STATUS=0)
BEGIN
	SELECT @GID = Id FROM Platform_BT.dbo.[User] WHERE Account = @Account
	UPDATE C6.dbo.Users SET YHID = @GID WHERE UserID = @C6ID
	FETCH NEXT FROM TEMP INTO @C6ID, @Account
END
CLOSE TEMP
DEALLOCATE TEMP