USE [C6]
GO


UPDATE C6.dbo.UsersInfo SET SmsNO = NULL
DECLARE @UserID nvarchar(100)
DECLARE @SmsNo int
SET @SmsNo = 0
DECLARE TEMP CURSOR FOR SELECT UserID FROM UsersInfo
OPEN TEMP 
FETCH NEXT FROM TEMP INTO @UserID
WHILE(@@FETCH_STATUS=0)
BEGIN
	SET @SmsNo = @SmsNo + 1
	UPDATE UsersInfo SET SmsNO = @SmsNo WHERE UserID = @UserID
	FETCH NEXT FROM TEMP INTO @UserID
END
CLOSE TEMP
DEALLOCATE TEMP